//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Res", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產生Excel報表.
        /// </summary>
        internal static string ButtonMakeExcelReport {
            get {
                return ResourceManager.GetString("ButtonMakeExcelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增明細.
        /// </summary>
        internal static string Button_Add_Detail {
            get {
                return ResourceManager.GetString("Button_Add_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變更密碼.
        /// </summary>
        internal static string Button_Change_Password {
            get {
                return ResourceManager.GetString("Button_Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇上傳檔案.
        /// </summary>
        internal static string Button_Choice_Files {
            get {
                return ResourceManager.GetString("Button_Choice_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇上傳圖片.
        /// </summary>
        internal static string Button_Choice_Images {
            get {
                return ResourceManager.GetString("Button_Choice_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認單據.
        /// </summary>
        internal static string Button_Confirm_Doc {
            get {
                return ResourceManager.GetString("Button_Confirm_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string Button_Insert {
            get {
                return ResourceManager.GetString("Button_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增明細.
        /// </summary>
        internal static string Button_Insert_Detail {
            get {
                return ResourceManager.GetString("Button_Insert_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        internal static string Button_Modify {
            get {
                return ResourceManager.GetString("Button_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列印.
        /// </summary>
        internal static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回前頁.
        /// </summary>
        internal static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回首頁.
        /// </summary>
        internal static string Button_ReturnIndex {
            get {
                return ResourceManager.GetString("Button_ReturnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 儲存.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 儲存,並送信.
        /// </summary>
        internal static string Button_SaveAndMail {
            get {
                return ResourceManager.GetString("Button_SaveAndMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋.
        /// </summary>
        internal static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始上傳檔案.
        /// </summary>
        internal static string Button_Start_FilesUp {
            get {
                return ResourceManager.GetString("Button_Start_FilesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始上傳圖片.
        /// </summary>
        internal static string Button_Start_ImagesUp {
            get {
                return ResourceManager.GetString("Button_Start_ImagesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        internal static string Button_Sure {
            get {
                return ResourceManager.GetString("Button_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定新增.
        /// </summary>
        internal static string Button_Sure_Insert {
            get {
                return ResourceManager.GetString("Button_Sure_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定修改.
        /// </summary>
        internal static string Button_Sure_Modify {
            get {
                return ResourceManager.GetString("Button_Sure_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直接入庫.
        /// </summary>
        internal static string Button_ToImport {
            get {
                return ResourceManager.GetString("Button_ToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT$.
        /// </summary>
        internal static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用中.
        /// </summary>
        internal static string C_product_state_NOR {
            get {
                return ResourceManager.GetString("C_product_state_NOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止使用.
        /// </summary>
        internal static string C_product_state_STP {
            get {
                return ResourceManager.GetString("C_product_state_STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1111.
        /// </summary>
        internal static string ePassword {
            get {
                return ResourceManager.GetString("ePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼長度不符(至少6個字元).
        /// </summary>
        internal static string Err_PasswordLength {
            get {
                return ResourceManager.GetString("Err_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼規則不符(需包含英、數位).
        /// </summary>
        internal static string Err_PasswordRule {
            get {
                return ResourceManager.GetString("Err_PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一頁.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變更密碼完成，下次登錄請使用新密碼。.
        /// </summary>
        internal static string Info_ChangePassword_Success {
            get {
                return ResourceManager.GetString("Info_ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉視窗.
        /// </summary>
        internal static string Info_Close_Layer {
            get {
                return ResourceManager.GetString("Info_Close_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料刪除完成.
        /// </summary>
        internal static string Info_Delete_Success {
            get {
                return ResourceManager.GetString("Info_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產品圖.
        /// </summary>
        internal static string Info_Detail_Picture {
            get {
                return ResourceManager.GetString("Info_Detail_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string Info_Edit {
            get {
                return ResourceManager.GetString("Info_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        internal static string Info_Home {
            get {
                return ResourceManager.GetString("Info_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料新增完成.
        /// </summary>
        internal static string Info_Insert_Success {
            get {
                return ResourceManager.GetString("Info_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定刪除？.
        /// </summary>
        internal static string Info_Is_SureDelete {
            get {
                return ResourceManager.GetString("Info_Is_SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上次登錄.
        /// </summary>
        internal static string Info_Last_Login {
            get {
                return ResourceManager.GetString("Info_Last_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申請加入中壢青商-{0}.
        /// </summary>
        internal static string Info_Mail_Title_JoinUs {
            get {
                return ResourceManager.GetString("Info_Mail_Title_JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能選單.
        /// </summary>
        internal static string Info_Menu {
            get {
                return ResourceManager.GetString("Info_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統回報訊息.
        /// </summary>
        internal static string Info_Toast_Return_Title {
            get {
                return ResourceManager.GetString("Info_Toast_Return_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料異動完成.
        /// </summary>
        internal static string Info_Trans_Success {
            get {
                return ResourceManager.GetString("Info_Trans_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料更新完成.
        /// </summary>
        internal static string Info_Update_Success {
            get {
                return ResourceManager.GetString("Info_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統錯誤.
        /// </summary>
        internal static string js_Err_System_Failure {
            get {
                return ResourceManager.GetString("js_Err_System_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後頁.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法登錄!狀態不符。.
        /// </summary>
        internal static string Login_Err_Normal {
            get {
                return ResourceManager.GetString("Login_Err_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法登錄!請重輸入帳號或密碼。.
        /// </summary>
        internal static string Login_Err_Password {
            get {
                return ResourceManager.GetString("Login_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳號已存在，不可使用。.
        /// </summary>
        internal static string Log_Err_AccountExists {
            get {
                return ResourceManager.GetString("Log_Err_AccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此{0}不存在,請重新選擇!謝謝~!.
        /// </summary>
        internal static string Log_Err_AddCart_Exist {
            get {
                return ResourceManager.GetString("Log_Err_AddCart_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此檔案類型不在充許範圍。.
        /// </summary>
        internal static string Log_Err_AllowFileType {
            get {
                return ResourceManager.GetString("Log_Err_AllowFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購物車內無此商品~!.
        /// </summary>
        internal static string Log_Err_Cart_ProductExist {
            get {
                return ResourceManager.GetString("Log_Err_Cart_ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此筆資料已結案!無法刪除!!.
        /// </summary>
        internal static string Log_Err_Delete_Close {
            get {
                return ResourceManager.GetString("Log_Err_Delete_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此筆資料無法刪除!刪除主檔前需先刪除明細檔或其他參照檔。.
        /// </summary>
        internal static string Log_Err_Delete_DetailExist {
            get {
                return ResourceManager.GetString("Log_Err_Delete_DetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要刪除的資料不存在。.
        /// </summary>
        internal static string Log_Err_Delete_NotFind {
            get {
                return ResourceManager.GetString("Log_Err_Delete_NotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案數量超過限制。.
        /// </summary>
        internal static string Log_Err_FileCountOver {
            get {
                return ResourceManager.GetString("Log_Err_FileCountOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案容量超過限制。.
        /// </summary>
        internal static string Log_Err_FileSizeOver {
            get {
                return ResourceManager.GetString("Log_Err_FileSizeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此節仍其下仍有資料，需先刪除其下節點才能刪除此節點。.
        /// </summary>
        internal static string Log_Err_HasSubTreeData {
            get {
                return ResourceManager.GetString("Log_Err_HasSubTreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸入的驗證碼不正確，請重新輸入。.
        /// </summary>
        internal static string Log_Err_ImgValideNotEquel {
            get {
                return ResourceManager.GetString("Log_Err_ImgValideNotEquel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該檔案類型禁止上傳。.
        /// </summary>
        internal static string Log_Err_LimitedFileType {
            get {
                return ResourceManager.GetString("Log_Err_LimitedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統錯誤，無任何資料傳出。.
        /// </summary>
        internal static string Log_Err_MustHaveData {
            get {
                return ResourceManager.GetString("Log_Err_MustHaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認密碼和新密碼不一致，請重新輸入。.
        /// </summary>
        internal static string Log_Err_NewPasswordNotSure {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordNotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密碼和舊密碼不可相同。.
        /// </summary>
        internal static string Log_Err_NewPasswordSame {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統無此使用者。.
        /// </summary>
        internal static string Log_Err_NoThisUser {
            get {
                return ResourceManager.GetString("Log_Err_NoThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未選擇客戶.
        /// </summary>
        internal static string Log_Err_Not_Select_Customer {
            get {
                return ResourceManager.GetString("Log_Err_Not_Select_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未選擇廠商.
        /// </summary>
        internal static string Log_Err_Not_Select_Supplier {
            get {
                return ResourceManager.GetString("Log_Err_Not_Select_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼不正確，請重新輸入。.
        /// </summary>
        internal static string Log_Err_Password {
            get {
                return ResourceManager.GetString("Log_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列印報表需輸入正確查詢條件。.
        /// </summary>
        internal static string Log_Err_PrintCondition {
            get {
                return ResourceManager.GetString("Log_Err_PrintCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該產品序號已存在。.
        /// </summary>
        internal static string Log_Err_ProdSerialExists {
            get {
                return ResourceManager.GetString("Log_Err_ProdSerialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此筆訂單編號不存在，請重新檢查訂單編號!.
        /// </summary>
        internal static string Log_Err_PurchaseExist {
            get {
                return ResourceManager.GetString("Log_Err_PurchaseExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此筆訂單編號已付款，請重新檢查訂單編號!.
        /// </summary>
        internal static string Log_Err_PurchaseRepeat {
            get {
                return ResourceManager.GetString("Log_Err_PurchaseRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫存不足.
        /// </summary>
        internal static string Log_Err_StockNotEnough {
            get {
                return ResourceManager.GetString("Log_Err_StockNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 庫存不足[{0}:{1}]，目前庫存數[{2}]。.
        /// </summary>
        internal static string Log_Err_Stock_NotEnough {
            get {
                return ResourceManager.GetString("Log_Err_Stock_NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一頁.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一頁.
        /// </summary>
        internal static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATEK JAPAN::Be your energy saving parter::.
        /// </summary>
        internal static string System_FrontName {
            get {
                return ResourceManager.GetString("System_FrontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATEK JAPAN 管理系統.
        /// </summary>
        internal static string System_Name {
            get {
                return ResourceManager.GetString("System_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無項目.
        /// </summary>
        internal static string ViewbagCapton {
            get {
                return ResourceManager.GetString("ViewbagCapton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能選單.
        /// </summary>
        internal static string ViewbagMenuName {
            get {
                return ResourceManager.GetString("ViewbagMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇要刪除的列。.
        /// </summary>
        internal static string Warn_Select_Delete_Data {
            get {
                return ResourceManager.GetString("Warn_Select_Delete_Data", resourceCulture);
            }
        }
    }
}
